### ISSUE TITLE
Plugin with id 'maven' not found.

### ISSUE THREAD

**Issue by alz10** [qonversion/react-native-sdk#103]
Any update to support `RN 0.67+`

```
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/user/Desktop/testapp (v0.67.3) - (v1)/testapp/node_modules/react-native-qonversion/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-qonversion'.
> Plugin with id 'maven' not found.
==============================================================================
2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-qonversion'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle
```

**Comment by SpertsyanKM** [comment]
Hello! Thanks for contacting us!

It seems like described problem relates to gradle 7+, where maven plugin was removed. We will get rid of it in our SDK soon - have already taken this task in work, but for now, you can downgrade your grade version to some version below 7 to make it compile successfully.

**Comment by alz10** [comment]
> Happy to inform you that we've just released the new version of react-native-qonversion library (3.2.1) without maven plugin. Please, try it and feel free to contact us if you face any problems.

Ok I'll try later

**Comment by alz10** [comment]
It's working now. Thanks!
