### ISSUE TITLE
Qonversion Data Safety

### ISSUE THREAD

**Issue by alz10** [qonversion/react-native-sdk#108]
Hello can you guys provide what `Data Types` you're collecting? This is actually required in the new Data Safety App Content. I don't know which data type should i check on. 

My app is purely offline so i don't collect data on my own, users just need internet connection to buy subscription and for the admob adverisement 

I receive an **"Action Required: Your app is not compliant with Google Play Policies"** from google and i think you're one of the culprit, hehe sorry for the word

**Revenue Cat** provided a doc already regarding this and i hope **Qonversion** can do this as soon as possible.
Sorry, I know this isn't related to the library but just want to open this to the public and inform other devs as well. Thank you!
https://docs.revenuecat.com/docs/google-plays-data-safety

<img width="494" alt="Screen Shot 2022-03-18 at 11 19 25 PM" src="https://user-images.githubusercontent.com/38030623/159030889-dd100a85-45cf-46b1-81b3-f93528c271c1.png">

**Comment by SpertsyanKM** [comment]
Hello! Thanks for contacting us.

We have a page for [App Store privacy](https://documentation.qonversion.io/docs/app-store-privacy) in our documentation. Please visit it, hope it will help you for now. And we also promise to create a corresponding page for Google Play as well, as soon as possible.

**Comment by alz10** [comment]
> Hello! Thanks for contacting us.
> 
> We have a page for [App Store privacy](https://documentation.qonversion.io/docs/app-store-privacy) in our documentation. Please visit it, hope it will help you for now. And we also promise to create a corresponding page for Google Play as well, as soon as possible.

Ohh ok, i didn't know it exist already. I've been reading and searching for `Data Safety` Thanks!
