### ISSUE TITLE
Configuration with name 'compile' not found.

### ISSUE THREAD

**Issue by huseyintamer** [qonversion/react-native-sdk#139]
Hello I got error when `npx react-native run-android`

Can you help me please ?

Version: "react-native-qonversion": "^3.3.1",
Device: Macbook Pro M1 (12.0.1)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/huseyintamer/Desktop/Hiface/LeanHiface/node_modules/react-native-qonversion/android/build.gradle' line: 82

* What went wrong:
A problem occurred configuring project ':react-native-qonversion'.
> Configuration with name 'compile' not found.

**Comment by SpertsyanKM** [comment]
Hello! Thank you for reporting this issue! 

The fix is on review now and will be released soon. I will additionally mention the release here when it will happen.

**Comment by SpertsyanKM** [comment]
Some info for those who will come here with the same problem - the issue relates to the new Gradle plugin version 7 where the 'compile' configuration was removed. So if you use it in your react-native project and the latest RN versions you will face this issue.

**Comment by SpertsyanKM** [comment]
Happy to announce that we have released the [new version](https://github.com/qonversion/react-native-sdk/releases/tag/3.3.2) of React Native Qonversion SDK - 3.3.2 - with a fix of the described problem.

I'm closing this issue, but feel free to reopen it or create new one if you have any further questions.
