### ISSUE TITLE
Build Failed with React Native 0.69.3 / react-native-qonversion 3.3.2

### ISSUE THREAD

**Issue by thibaultfischer** [qonversion/react-native-sdk#147]
Hello, 

We have an expo app and we just migrated to expo 46 which is shipped with react native 0.69.3.

When we try to build the app we get this error : 

<img width="911" alt="image" src="https://user-images.githubusercontent.com/92362985/183485518-8a7e8af5-2cfe-4e61-b4dc-a549b0b04a99.png">

In the documentation you say to install the package and run `react-native link react-native-qonversion`

But the `link` command does exist anymore in react native 0.69.X. I dont know if the build error is related or not.

[Here is a link to a minimal reproductible demo](https://github.com/tfisc/qonversion-error)

Run commands:
 `yarn`
`cd android`
`./gradlew assembleRelease` => Error. if you delete the qonversion package and try to build again you will see that the build is successful.

Thanks for your help.

**Comment by SpertsyanKM** [comment]
Hello! Thank you for your report! We will research it and will return to you with the result as soon as possible.

**Comment by SpertsyanKM** [comment]
Happy to introduce our new release with beautiful version [3.3.3](https://github.com/qonversion/react-native-sdk/releases/tag/3.3.3), which contains the fix to your problem. 

Thank you again for informing us! Feel free to reopen this issue or create a new one if you have any further problems.

**Comment by thibaultfischer** [comment]
Thanks you guys, that was so fast
