### ISSUE TITLE
iOS products are empty on new version

### ISSUE THREAD

**Issue by getadapt** [qonversion/react-native-sdk#173]
Since updating 3.4 -> 3.6, I'm getting empty products back in iOS in production, with the correct IDs but empty details, for example:

```
{
    "currencyCode": undefined,
    "duration": undefined,
    "offeringId": undefined,
    "prettyIntroductoryPrice": undefined,
    "prettyPrice": "",
    "price": undefined,
    "qonversionID": "unlock_themes",
    "skProduct": null,
    "skuDetails": null,
    "storeDescription": undefined,
    "storeID": "unlock_themes",
    "storeTitle": undefined,
    "trialDuration": "NOT_AVAILABLE",
    "type": "ONE_TIME"
}
```

Any ideas on this? Is there extra steps needed since the update that aren't documented?

I would send this as a support ticket on the Qonversion website, but the chat feature isn't working.

**Comment by suriksarkisyan** [comment]
Hi, @getadapt 
Thanks for contacting us.
Could you please show the code example? How did you get the products?
