### ISSUE TITLE
Issue during android build

### ISSUE THREAD

**Issue by thibaultfischer** [qonversion/react-native-sdk#193]
Hi guys, 

I'm using version 3.3.2 of the package.

Since Tuesday I cant build on android because of the following error: 
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/92362985/201034332-c71a71d0-c146-4df7-ae79-35376e38e8ac.png">

I did not change anything in my project, and I'm not using version 0.71.0-rc.0 of react native.
Any idea why this popped out of nowhere ?

Version of react native in my node_modules: 
<img width="555" alt="image" src="https://user-images.githubusercontent.com/92362985/201034644-ef148cb3-851e-4047-b552-85cd75f151e2.png">

Version of react-native-qonversion in my node_modules: 
<img width="522" alt="image" src="https://user-images.githubusercontent.com/92362985/201034750-8e0b0225-c160-4f80-98b2-1986ea0cbe40.png">

Thanks for your help :)

**Comment by SpertsyanKM** [comment]
Hello! 

There was an [issue](https://github.com/qonversion/react-native-sdk/issues/147) with this version and it has been fixed already. Please, consider upgrading the `react-native-qonversion` version to (at least) 3.3.3 or even newer. The latest version number is 3.6.2.

I'm closing this issue as a duplicate, but feel free to reopen or create new ones if you have further questions. 

Have a good day!
