### ISSUE TITLE
[ios] Don't complete apple in-app purchase after update to 2.3.0 version

### ISSUE THREAD

**Issue by iddar** [qonversion/react-native-sdk#21]
I make an apple in-app purchase with `Qonversion.purchase` method but not show a pay modal, just return a Permission object.  But never pay and the subscription status keeps the same. Not display an error o warn only don't work. 

I have a public version of my app in the app store with 2.0.2, I try rollback and wait for your answer.
I use React native with Hermes build option (works perfectly in the previous version)

All test make in the physical device iPhone 6 Plus
Xcode: Version 12.3 (12C33)

### Deps Version
```json
"react": "17.0.1",
"react-native": "0.64.0-rc.2",
"react-native-qonversion": "2.3.0",
```

**Comment by suriksarkisyan** [comment]
Hi @iddar 
Thank you for the report. I will try to reproduce and come back asap

**Comment by iddar** [comment]
If you need anything else, or I can help in another way, just let me know. 

Thank you very much for your prompt reply.

**Comment by suriksarkisyan** [comment]
Thanks, I will ask you if needed 🤜🤛

**Comment by suriksarkisyan** [comment]
Hi again @iddar 
Sorry for the delayed response.
I tried to reproduce your case. Unsuccessfully. For me, purchase flow works well
Can you please provide more information? 
Also, make sure you are using the correct Qonversion product ID for purchase.

**Comment by iddar** [comment]
Thanks for your work, I try insolated a problem in my next dependencies update. 

Close this issue, if show a big again return to this. 

Have a nice day.

**Comment by suriksarkisyan** [comment]
Deal. Let's keep in touch! ✌️
Have a nice day!
