### ISSUE TITLE
skProduct is null

### ISSUE THREAD

**Issue by kyle-ssg** [qonversion/react-native-sdk#213]
Hello! Setting up a new iOS application I am seeing that skProduct is always null

Request:
```
const products = await Qonversion.getSharedInstance().products()
```

Response: 
```
[
  {
    "qonversionID": "workout_annual",
    "storeID": "workout_annual",
    "type": "DIRECT_SUBSCRIPTION",
    "duration": "ANNUAL",
    "skuDetails": null,
    "skProduct": null,
    "prettyPrice": "",
    "trialDuration": "UNKNOWN"
  },
  {
    "qonversionID": "workout",
    "storeID": "workout",
    "type": "ONE_TIME",
    "skuDetails": null,
    "skProduct": null,
    "prettyPrice": "",
    "trialDuration": "UNKNOWN"
  },
  {
    "qonversionID": "workout_monthly",
    "storeID": "workout_monthly",
    "type": "DIRECT_SUBSCRIPTION",
    "duration": "MONTHLY",
    "skuDetails": null,
    "skProduct": null,
    "prettyPrice": "",
    "trialDuration": "UNKNOWN"
  }
]
```

Based on https://github.com/qonversion/qonversion-ios-sdk/issues/101 I can validate the following:

```
Your in-app purchases are not configured correctly on the App Store Connect. Check the first point of this section.
```

I believe they are, here they are 

![image](https://user-images.githubusercontent.com/8608314/213253890-8d0dc0b7-0572-41ae-bfe5-7a6fdfce08b2.png)
![image](https://user-images.githubusercontent.com/8608314/213253979-81a629d5-40dc-41c9-a4e4-71647edba3ec.png)

```
Your app bundle ID does not match the bundle ID from App Store Connect where purchases were created.
```

It does:

![image](https://user-images.githubusercontent.com/8608314/213256037-d15bc581-e5ac-47b0-8abe-7bf928dbe0fe.png)
![image](https://user-images.githubusercontent.com/8608314/213256287-aa0da37c-9370-4a0b-856f-a4767faccba6.png)
![image](https://user-images.githubusercontent.com/8608314/213256551-b2f3efba-1b5c-47e6-9491-01522e13030c.png)
![image](https://user-images.githubusercontent.com/8608314/213256678-4d27e4bf-cae0-4e52-b31b-a9466169dd67.png)

```
You are using .storekit file which is configured with other IDs than you are trying to use.
```

We are not using a storekit file.

**Comment by SpertsyanKM** [comment]
Hello! Thank you for contacting us. While we are investigating your problem, could you please clarify which version of Qonversion react-native SDK are you using?

**Comment by kyle-ssg** [comment]
"react-native-qonversion": "^4.0.0",

kyle@solidstategroup.com is the account with the project name Built by Becky

**Comment by SpertsyanKM** [comment]
Thank you for the information! I'll return as soon as I get any details.

**Comment by SpertsyanKM** [comment]
I've checked our sample app and everything works fine - I receive products on iOS with `SKProduct` data included.

Could you please check whether your application identifier in XCode is the same as in AppStoreConnect?
<img width="1025" alt="Снимок экрана 2023-01-19 в 13 38 26" src="https://user-images.githubusercontent.com/13959241/213421205-e0a52c07-2201-4b75-9937-860545047b5f.png">

Also, please, make sure, that you are testing on a real device, not a simulator, as App Store not working on simulators.

**Comment by kyle-ssg** [comment]
Hey @SpertsyanKM, I've been testing the app from TestFlight so yeah it has to be

**Comment by SpertsyanKM** [comment]
Also, please take a look at the app logs as there might be some useful information after initialization about fetching store products.

**Comment by kyle-ssg** [comment]
Ok so I get back 

```
Invalid store products identifiers: (
    "workout_monthly",
    workout,
    "workout_annual",
    "bbb_workout_quarterly"
)
```

**Comment by SpertsyanKM** [comment]
Well, we were unable to load info about all your identifiers, which means that the problem is global. It could be one of the described in your start post or incorrect iOS bundle identifier (please, double check it - in most cases it is the problem). If you are sure, that everything is set up correctly, try to test on another real device.

**Comment by kyle-ssg** [comment]
I could be wrong but I'm wondering if every section in https://appstoreconnect.apple.com/agreements/#/ needs to be filled out and a bank account needs to be attached. Our other org has this which has a working example. 
<img width="566" alt="image" src="https://user-images.githubusercontent.com/8608314/213474260-64eb4b84-5067-41af-9763-6ca999e42b88.png">

**Comment by SpertsyanKM** [comment]
Seems like it shouldn't be necessary for testing.

**Comment by kyle-ssg** [comment]
I'd have thought so too, but from reading around it seems like you have to enter tax and banking info.

**Comment by kyle-ssg** [comment]
Yep of course, I'll report back if that's the issue. But reading around I have seen people report invalid product skus due to this.

**Comment by kyle-ssg** [comment]
That was the issue! Thanks very much for your prompt responses

**Comment by jeky1990** [comment]
@kyle-ssg @SpertsyanKM 
can u help me i got same error what u received.

its must needed to fill all below data in app store.
https://appstoreconnect.apple.com/agreements

**Comment by SpertsyanKM** [comment]
Yes, you should fill it

**Comment by jeky1990** [comment]
Thanks... Fro quick answer.
will let u know if this works.
