### ISSUE TITLE
Question: Does Qonversion finish consumable purchases? If not, how would I do this?

### ISSUE THREAD

**Issue by kyle-ssg** [qonversion/react-native-sdk#214]
I intend on using consumable purchases to give user access to a digital product, I can see brief mentions of consumable products but am quite unclear on how this works.

Does Qonversion have the ability to mark purchases as consumed (e.g. https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/finishing_a_transaction) and whatever equivilent for Android?

**Comment by kyle-ssg** [comment]
As a side note I noticed this on iOS, perhaps the react-native client auto finishes purchases?

https://github.com/qonversion/qonversion-ios-sdk/issues/247

**Comment by suriksarkisyan** [comment]
Hi, @kyle-ssg 
Thanks for contacting us. Our SDK's finish transactions (for iOS) and consume/acknowledge purchases (for Android) if you are using our SDK in the Infrastructure mode. And you should finish/acknowledge/consume purchases by yourself if you use us in the Analytics mode.

**Comment by kyle-ssg** [comment]
Ok thanks, I think that means "SubscriptionManagement" mode, at least that's what the SDK calls the other option. Thanks!
