### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by hanakslr** [qonversion/react-native-sdk#24]
Hi, I was wondering if there are any plans to add typescript support? The current index.js throws a bunch of errors in my IDE because it contains type annotations in a .js file. I put a definition file together to avoid some runtime type errors - [the gist is here](https://gist.github.com/hanakslr/b959bf9761bc100989a2c0d689472aef). I can submit a proper pull request, but have never written a definition file before so it probably shouldn't be taken at face value.

Other than that am enjoying how smooth the integration is going!

**Comment by suriksarkisyan** [comment]
Hi @hanakslr 
Thank you so much, we are happy you like our service.
Yes, we will add typescript support in the next few weeks. I will not promise you a concrete day, but we will do it ASAP. 
Keep for updates 🤝

**Comment by spotelf13** [comment]
@suriksarkisyan what is the eta on TS support?

**Comment by suriksarkisyan** [comment]
Hi, @spotelf13 
TS support will be available in the next few days. Keep in touch😊

**Comment by suriksarkisyan** [comment]
Hi guys. Happy to say [React Native SDK 2.5.0](https://www.npmjs.com/package/react-native-qonversion) with TypeScript support is released.
