### ISSUE TITLE
Failure to retrieve SkuDetails for the in-app product ID

### ISSUE THREAD

**Issue by Fr33maan** [qonversion/react-native-sdk#25]
https://stackoverflow.com/questions/66136093/how-to-successfully-do-in-app-purchases-with-qonversion-or-iap-hub-on-react-nati

I'm unable to make a purchase, when calling `await Qonversion.purchase('monthly')`, I get the following error:

`[Error: Failure to retrieve SkuDetails for the in-app product ID]`  

The product exists in Google Play and **IS active**.

I'm completely clueless on what I should do next.

**Comment by suriksarkisyan** [comment]
Hi, @Fr33maan 
Could you please check this [part of our documentation](https://documentation.qonversion.io/docs/troubleshooting#2-skudetails-error-android-only). If the problem still occurs, provide please your email address which one used for registration in our service.

**Comment by suriksarkisyan** [comment]
@Fr33maan 
Use this one please `s.sarkisyan@qonversion.io`

**Comment by suriksarkisyan** [comment]
@Fr33maan thank you for the reply
Could you please call `Qonversion.products()` and show the result? Especially `skProduct` properties of `QProducts`

**Comment by Fr33maan** [comment]
While I was getting a response from the backend in my last attempt with a `skProduct: null`, now I'm not even able to init the sdk and get `Error: There was a backend error` when I'm calling the init function of the SDK with:  
`await Qonversion.launchWithKey(QONVERSION_PROJECT_KEY, false)`

**Comment by suriksarkisyan** [comment]
@Fr33maan thanks, got it
I need a little bit more time. I'll try to reproduce your problem and come back with an answer.

**Comment by suriksarkisyan** [comment]
@Fr33maan I tried to reproduce the error. 
For me, all works fine. I get the skuDetails for your project successfully.
Could you please provide more details about your flow?
But at first, try to delete and reinstall your app, clean the cache and app data for the Google play store and make sure you logged into the Google Play Store using the correct account.

**Comment by Fr33maan** [comment]
Ok I got it.
The mistake was in the build.gradle file, I had an `applicationIdSuffix` in the debug buildType.
I got rid of the suffix and I'm now able to find the `skuDetails`.

Thanks for your help !

**Comment by suriksarkisyan** [comment]
@Fr33maan 👍
I will be grateful if you leave a link to this issue on stackoverflow. So other users who have the same issue will be able to find the fix.
