### ISSUE TITLE
Add price-related fields

### ISSUE THREAD

**Issue by yzlin** [qonversion/react-native-sdk#26]
Is it possible to add price-related fields like `price`, `instroductoryPrice`, `currencyCode`, `currencySymbol` so we don't have to dig into `skProduct` & `skuDetail`.

**Comment by suriksarkisyan** [comment]
Hi, @yzlin 
I think yes, we can add that fields. I can not promise you a concrete date, but I will add a ticket for our dev team.
Also, if you want, you can do it by yourself. We will be happy to review your pull request.

**Comment by suriksarkisyan** [comment]
Hi @yzlin 
Happy to say that your PR is released as [2.4.0](https://github.com/qonversion/react-native-sdk/releases/tag/2.4.0)
Thank you so much for your contribution!
