### ISSUE TITLE
Entitlement data after purchase

### ISSUE THREAD

**Issue by darimuhittinhey** [qonversion/react-native-sdk#271]
Platform : IOS
react-native-qonversion : "^6.2.0"
react-native : "0.70.6"

I have a function to subscribe

```ts
 const subscribe = async () => {
    dispatch(SET_LOADING(true));
    try {
      const selected = products?.find(
        prod => prod.qonversionID === (selectedId === 1 ? 'monthly' : Platform.OS === 'ios' ? 'yearly' : 'sixmonths'),
      );
      if (selected) {
        const entitlements: Map<string, Entitlement> =
          Platform.OS === 'ios'
            ? await Qonversion.getSharedInstance().purchaseProduct(selected)
            : await Qonversion.getSharedInstance().purchase(selected.qonversionID);

        if (entitlements.keys()) {
          for (const [key, value] of entitlements.entries()) {
            reactotron.log?.('key', key);
            reactotron.log?.('value', value);
          }
        }
        reactotron.log?.('entitlements', entitlements);
      }
    } catch (e: any) {
      if (e.userCanceled) {
        // Purchase canceled by the user
        reactotron.log?.('Purchase canceled by the user');
      }
      reactotron.log?.('error in subscribe', e);
    }
    dispatch(SET_LOADING(false));
  };
```

and when i log returned entitlements i got this :

<img width="451" alt="image" src="https://github.com/qonversion/react-native-sdk/assets/136324959/60626c6f-c817-4f46-9508-cdc3967fc6ad">

this is my entitlement:

<img width="1104" alt="image" src="https://github.com/qonversion/react-native-sdk/assets/136324959/68036359-4bbf-409e-85f9-0df1ca580f8c">

and the docs says that Entitlement object is like this :

<img width="856" alt="image" src="https://github.com/qonversion/react-native-sdk/assets/136324959/17025588-f8e8-4c15-a72a-f984d9b569b4">

But if we look into Entitlement class in react-native-conversion package:

<img width="948" alt="image" src="https://github.com/qonversion/react-native-sdk/assets/136324959/84f10a02-5543-4278-904a-b4350685b895">

i need other information as docs says. Like transaction id or purchaseToken (for android) of purchase.

whats the point in here ? am i missing something ?

**Comment by suriksarkisyan** [comment]
Hi, @darimuhittinhey 
Those fields are available for iOS and Android SDK's. We are working on a release for RN SDK that will be available in the next few days. Let's keep in touch. I'll come back with an update after the release.

**Comment by suriksarkisyan** [comment]
Hi, @darimuhittinhey 
I am happy to say that the new version [6.3.0](https://github.com/qonversion/react-native-sdk/releases/tag/6.3.0) has arrived!
