### ISSUE TITLE
Failed to start screen with id [..] with exception: java.lang.RuntimeException: Failure from system

### ISSUE THREAD

**Issue by devnm21** [qonversion/react-native-sdk#299]
Error: 
```
Failed to start screen with id zoQ7-Vwz with exception: java.lang.RuntimeException: Failure from system
```

Just trying to launch a screen that's created on the dashboard, but unable to.
Same code works on iOS. 

`Automations.getSharedInstance().showScreen("zoQ7-Vwz");`

RN Version: `0.72.6`
react-native-qonversion: `7.4.0`.

Things tried:
1. Deleting and Installing node modules again
2. Doing the first step along with reinstalling/rebuilding the app

Has anyone faced this issue? There seems to be no references to this particular error so far.

**Comment by SpertsyanKM** [comment]
Hello! Thank you for the report. I'll dig deeper into your case and will return as soon as I have any news

**Comment by SpertsyanKM** [comment]
The problem with that screen is the huge size of the content set (probably the image). While we are working on fixing this issue, you can try to optimize the image you add to the screen to fix the problem on your side.

Thanks for contacting us and feel free to reopen the issue if the problem persists.
