### ISSUE TITLE
Adding `resetUser` method

### ISSUE THREAD

**Issue by AlexeyVlasenko** [qonversion/react-native-sdk#30]
Greetings!
Are you working on implementing `resetUser` method in RN SDK?
Or I can implement it and create a PR?

**Comment by suriksarkisyan** [comment]
Hi, @AlexeyVlasenko 
`resetUser` is deprecated and will be removed soon🙂
In case if you need to reset the user you can delete him from customers on [Qonversion dashboard](https://dash.qonversion.io/customers/index)

**Comment by AlexeyVlasenko** [comment]
Greetings, @suriksarkisyan
Thanks for reply!

If it will be removed, how can I handle multi-account in app then?
I thought I should resetUser on user logout to perfectly handle this situation.

**Comment by suriksarkisyan** [comment]
We are working now on a new identity concept that will be available soon.
We will add `logout()` function for a new concept.
Keep for updates 🤜🤛
