### ISSUE TITLE
No virtual method ToString in class Lokhttp3/Cookie

### ISSUE THREAD

**Issue by jfbn** [qonversion/react-native-sdk#31]
I'm trying to install this library so that we can use it in Observer mode alongside IAPHub.

Launching the app on Android will cause a crash without any error messages being sent.
Luckily I was able to track down the issue with sentry.

> NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in /data/app/com.gamerzclass.gamerzclassmembers-NXTfYo4m0itGOWA7suy2CA==/base.apk!classes4.dex)

It appears that I some part of this library is trying to use a method from https://square.github.io/okhttp/ - I'm just confused as to why this dependency is not either automatically installed or mentioned as a requirement in the [getting started](https://documentation.qonversion.io/docs/react-native-sdk) articles.

I have scheduled a technical support call with Qonversion tomorrow to address concerns unrelated to this issue. I do however intend to refer to this issue during the call to clear things up.

**Comment by Maria-Bordunova** [comment]
Hello, @jfbn. Sorry for the late response :pleading_face:. The problem should be fixed since sdk version 2.4.1 .

If you still have problems, please contact us.

**Comment by b0n1q** [comment]
have you solved the issue?

**Comment by suriksarkisyan** [comment]
Hi, @b0n1q 
Yes, use the latest version of SDK, please.
