### ISSUE TITLE
iOS problem - Methods that return promises must accept a RCTPromiseResolveBlock

### ISSUE THREAD

**Issue by Mirott** [qonversion/react-native-sdk#340]
Hi. While running the iOS project on RN + Expo, I received the following error:

_Error: Exception in HostObject::get for prop 'RNQonversion': Failed to create module "RNQonversion": Error while parsing method RNQonversion.attachUserToExperiment: Methods that return promises must accept a RCTPromiseResolveBlock followed by a RCTPromiseRejectBlock. This method accepts a RCTResponseSenderBlock followed by a RCTPromiseRejectBlock._

GPT advised me to modify the code in this way and it helped

From:
```
RCT_EXPORT_METHOD(attachUserToExperiment:(NSString *)experimentId groupId:(NSString *)groupId completion:(RCTResponseSenderBlock)completion rejecter:(RCTPromiseRejectBlock)reject) {
    [_qonversionSandwich attachUserToExperimentWith:experimentId groupId:groupId completion:^(NSDictionary<NSString *,id> * _Nullable result, SandwichError * _Nullable error) {
        [self handleResult:result error:error completion:completion rejecter:reject];
    }];
}
```
To:
```
RCT_EXPORT_METHOD(attachUserToExperiment:(NSString *)experimentId groupId:(NSString *)groupId resolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject) {
    [_qonversionSandwich attachUserToExperimentWith:experimentId groupId:groupId completion:^(NSDictionary<NSString *,id> * _Nullable result, SandwichError * _Nullable error) {
        if (error) {
            reject(@"attach_user_to_experiment_error", @"Failed to attach user to experiment", error);
        } else {
            resolve(result);
        }
    }];
}
```
This helped to eliminate the error display.

This also applies to the other methods available in the files **RNQonversion.m** and **RNAutomations.m**

**Comment by SpertsyanKM** [comment]
Hello @Mirott.

Are you using Expo Go or Development Builds? Qonversion SDK is [incompatible](https://documentation.qonversion.io/docs/react-native-sdk#running-with-expo) with Expo Go

**Comment by Mirott** [comment]
> Hello @Mirott.
> 
> Are you using Expo Go or Development Builds? Qonversion SDK is [incompatible](https://documentation.qonversion.io/docs/react-native-sdk#running-with-expo) with Expo Go

I am using **Development Builds**

**Comment by SpertsyanKM** [comment]
Could you please share your RN and Expo version?

**Comment by Mirott** [comment]
> Could you please share your RN and Expo version?

Sure.

   "expo": "~52.0.11",
   "react-native": "0.76.3",

```
import Qonversion, {
    QonversionConfigBuilder,
    LaunchMode,
    Product,
    Entitlement,
} from 'react-native-qonversion';
```

**Comment by SpertsyanKM** [comment]
Thank you for the information! We’ll review it and get back to you as soon as we have any updates.

**Comment by SpertsyanKM** [comment]
Hi @cristianrosu, I apologize for the delayed reply. We’re still looking into this and will update you as soon as we have more information. Thank you for your patience!

**Comment by SpertsyanKM** [comment]
I apologize once again for the delay in addressing this issue. I understand how important it can be for you. The developer who was handling this problem has taken a forced leave, and the resolution is temporarily on hold. I am currently trying to take over the task and hope to provide a solution soon.

**Comment by daltonlet** [comment]
> @SpertsyanKM that solved* the issue and I could run the project. However, I realised now that migrating `react-native-qonversion` from `7.5.2` to `8.x` I get into another big issues, offerings & products are not returned anymore.
> 
> Nothing else has changed, only updated the package. I also tested on a previous build using react native 0.73 (old architecture). qonversion 7.5.2 works fine, updating to `8.2.1`, `8.2.0` not. Also tested `8.1.5`, same issue. Offerings come null from the sdk, no products to display on the paywall.
> 
> I double checked migration guides. Do you guys have a working demo with 8.x version of the package?

Hi everyone, I'm having the same issue here on react-native 0.74.5 with `react-native-qonversion` 8.2.1. Still been unable to retrieve products or offerings via the SDK. I will try downgrading to `7.5.2` and see if that helps.

**Comment by suriksarkisyan** [comment]
Hi @cristianrosu 
We are currently investigating the issue and will try to resolve it as soon as possible.

**Comment by suriksarkisyan** [comment]
I’m pleased to announce that version [8.2.2](https://github.com/qonversion/react-native-sdk/releases/tag/8.2.2) has officially been released! Could you take a moment to test it out and let me know if everything is functioning as expected? Thank you!
