### ISSUE TITLE
Display and purchase in app purchases

### ISSUE THREAD

**Issue by elmcapp** [qonversion/react-native-sdk#5]
Using react native are we able to display product (subscriptions).
Using react native are we able to purchase in app (in app purchases)

following the documentation I did not see any codes on how to do this. Only saw code for setup with react native but nothing to do the two task above, only swift and obj c.

Do you have plans to provide code to do this in react native and as well as a full working example for use review

**Comment by smejl** [comment]
Hi @elmcapp! 

We've released version 2.0.0 with Product Center.

You can display products using something like this:

```js
const products: Map<string, Product> = await Qonversion.products();
```

You can start making purchases with the purchase method as follows:
```js
try {
  const permissions: Map<string, Permission> = await Qonversion.purchase('main');
} catch (e) {
  console.log(e);
}
```

Read more [here](https://documentation.qonversion.io/docs/displaying-products)
