### ISSUE TITLE
Can't purchase expired subscription

### ISSUE THREAD

**Issue by ilya-bmi** [qonversion/react-native-sdk#57]
When I call "qonversion.purchase" for an expired subscription it returns permissions, but not initialize a new purchase. How to subscribe to the same product again?

 const products = await qonversion.purchase("app.week");

data returned:
{
permissionID:'app.week'
productID:'app.week'
expirationDate:1621442782000
isActive:false
renewState:2
startedDate:1621424788000
}

**Comment by suriksarkisyan** [comment]
Hi @ilya-bmi 
Could you please provide more information?
SDK version, OS and userID?

**Comment by ilya-bmi** [comment]
OS: IOS 13.5.1
SDK: 2.5.0
What is the userID ?

**Comment by suriksarkisyan** [comment]
So for the first purchase, all works fine, yes? 
When the purchase expired, you cannot purchase it again, right?
And it still not works after relaunch and permission still inactive?
I'll try to reproduce and come back with a solution

**Comment by suriksarkisyan** [comment]
@ilya-bmi could you please mail me your company or application name on `s.sarkisyan@qonversion.io`?
