### ISSUE TITLE
Add setIdentify method to restrict same subscription to be used on multiple account 

### ISSUE THREAD

**Issue by bick111** [qonversion/react-native-sdk#59]
Please add above feature

**Comment by suriksarkisyan** [comment]
Hi, @bick111 
This feature is already done and will be released today 😊

**Comment by suriksarkisyan** [comment]
Hi, @bick111 
[Release 2.6.0](https://github.com/qonversion/react-native-sdk/releases/tag/2.6.0) published 🎉
