### ISSUE TITLE
Debug mode for React Native SDK

### ISSUE THREAD

**Issue by Fr33maan** [qonversion/react-native-sdk#7]
I need to test but not able to do:

```
TypeError: _reactNativeQonversion.default.setDebugMode is not a function. (In '_reactNativeQonversion.default.setDebugMode()', '_reactNativeQonversion.default.setDebugMode' is undefined)
```

**Comment by suriksarkisyan** [comment]
Hi, @Fr33maan 
Debug mode for rn already done and will be released ASAP. Maybe tomorrow or on Monday.
I will let you know)

**Comment by Fr33maan** [comment]
Nice job !

**Comment by suriksarkisyan** [comment]
Hi again, @Fr33maan 
Debug mode support is [released](https://www.npmjs.com/package/react-native-qonversion)
Just update Qonversion to 2.1.0 version 😉
