### ISSUE TITLE
Handling Pending Payments

### ISSUE THREAD

**Issue by sonivaibhav27** [qonversion/react-native-sdk#83]
Hi , Thanks for the wonderful service you guys provide . I have a question about how to handle pending /Deferred payment with Play store because there is no react-native example in the docs of qonversion?

**Comment by suriksarkisyan** [comment]
Hi @sonivaibhav27 
Thank you for the feedback 🖤
Unfortunately, that feature doesn't release for RN SDK right now. We'll add deferred purchases support soon.

**Comment by suriksarkisyan** [comment]
Hi, @sonivaibhav27 
Sorry for the late reply. Deferred and pending purchases feature implemented and available in the [latest version of RN SDK](https://github.com/qonversion/react-native-sdk/releases/tag/3.3.0)
