### ISSUE TITLE
Cannot install in RN 0.65 with React 17.0.2

### ISSUE THREAD

**Issue by cristianrosu** [qonversion/react-native-sdk#84]
Installing this in a new react native project throws this error.

```
Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.1" from react-native-qonversion@3.1.1
npm ERR! node_modules/react-native-qonversion
npm ERR!   react-native-qonversion@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by suriksarkisyan** [comment]
Hi, @cristianrosu ✌️
Could you show your package.json file, please?
If you don't want to publish it, you can text me at: s.sarkisyan@qonversion.io

**Comment by LaVey1337** [comment]
maybe need to update react version in react-native-qonversion from 16.8.1 to latest
or
use `npm i react-native-qonversion --force`

**Comment by Maria-Bordunova** [comment]
Hi again @cristianrosu 
Were you able to get rid of the error?

**Comment by pixelfoxxx** [comment]
Hello @cristianrosu ! We still didn’t get any reply from you regarding the issue above. We’ll close this issue for the time being.

Feel free to contact us if you have any further questions or if the issue persists. We’ll be glad to assist!
