### ISSUE TITLE
Permission object having active flag to false

### ISSUE THREAD

**Issue by sonivaibhav27** [qonversion/react-native-sdk#86]
I have made a real purchase with Card , and i was successfully using My Premium features within the app `Permission Object having Active flag to true`, but when i refund the order from OrderManagement Page Google Play Console and then again i purchased the premium feature amount was deducted and got successful purchase message but `Permission Active flag was set to false` , what may be the issue?

Qonversion SDK : ^3.1.1
React Native : 0.63.4

ps: I have checked the Revoke Entitlement checkbox while refunding the order

**Comment by pixelfoxx** [comment]
@sonivaibhav27 Hello, we've released a fix regarding your issue, so now everything should be working fine. You can try to repeat the scenario and contact us if the issue persists.
