### ISSUE TITLE
IAP receipt error

### ISSUE THREAD

**Issue by kilimchoi** [qonversion/react-native-sdk#87]
Hi,

I've received this message from an app reviewer saying that IAP purchase resulted in an error prompt showing up with this error message `No matching receipt found`

Personally I have been unable to reproduce this issue and I was wondering if anyone has seen this before. If so, how do we resolve this issue? 

I'm using 
react-native^0.64.1
react-native-qonversion^2.7.0
![Screen Shot 2021-11-02 at 8 53 56 PM](https://user-images.githubusercontent.com/1356007/139971880-6a0946d2-022d-4d7b-b1dd-24115cdb4eb0.png)

**Comment by Maria-Bordunova** [comment]
Hi @kilimchoi 
Does the issue still exist? Were you able to pass the review?

**Comment by pixelfoxxx** [comment]
Hello @kilimchoi! We still didn’t get any reply from you regarding the issue above. We’ll close this issue for the time being.
Feel free to contact us if you have any further questions or if the issue persists. We’ll be glad to assist!
