### ISSUE TITLE
React-native linking deprecation warning

### ISSUE THREAD

**Issue by pixarfilmz112** [qonversion/react-native-sdk#91]
Hello, and happy new year 🥳 ! I am not really sure if this is an issue but here it is.

When running the command `npx react-native link react-native-qonversion` from [https://documentation.qonversion.io/docs/react-native-sdk](url), I get the following warning: 

> $ npx react-native link react-native-qonversion
> warn Calling react-native link [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
> Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
> info Linking "react-native-qonversion" iOS dependency
> info iOS module "react-native-qonversion" has been successfully linked
> info Linking "react-native-qonversion" Android dependency
> info Android module "react-native-qonversion" has been successfully linked

Is this something to look out for ?

Thank you.

**Comment by suriksarkisyan** [comment]
Hi, @pixarfilmz112 
That is the warning related to npx react-native link. You could check [this link](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) for more info 😊
